# This is a basic workflow to help you get started with Actions
name: Deploy to AWS

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "us-east-1" #Change to reflect your Region
  DEVICE_PUSH_ID: ${{ secrets.DEVICE_PUSH_ID }}

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeOIDCroleAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::806575005518:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Bundle Lambda and Deploy CDK
        run: |
          npm install
          export DEVICE_PUSH_ID=$DEVICE_PUSH_ID
          
          # Install AWS CDK globally and deploy the CDK stack
          npm install -g aws-cdk
          cdk deploy --app "node cdk.js"
